import { StyleSheet } from "@react-pdf/renderer";
import moment from "moment";

export const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    paddingTop: 35,
    paddingBottom: 65,
    paddingLeft: 27,
    paddingRight: 30,
    fontSize: 9,
  },
  headerTitle: {
    fontFamily: "Helvetica-Bold",
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  headerTitleContent: {
    fontFamily: "Helvetica-Bold",
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  sectionProducts: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerClientName: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerCell: {
    flexGrow: 1,
    flexBasis: 0,
    textDecoration: "underline",

    textTransform: "capitalize",
    marginBottom: 5,
    marginTop: 5,
  },
  headerCell2: {
    flexGrow: 2,
    flexBasis: 0,
    textDecoration: "underline",
    textTransform: "capitalize",
    marginBottom: 5,
    marginTop: 5,
  },
  headerCell3: {
    flexGrow: 3,
    flexBasis: 0,
    textDecoration: "underline",
    textTransform: "capitalize",
    marginBottom: 5,
    marginTop: 5,
  },
  sectionProductsContent: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  contentCell: {
    flexGrow: 1,
    flexBasis: 0,
    paddingBottom: 3,
  },
  contentCell2: {
    flexGrow: 2,
    paddingBottom: 3,
    flexBasis: 0,
  },
  contentCell3: {
    flexGrow: 3,
    flexBasis: 0,
    paddingBottom: 3,
  },
  uppercase: {
    textTransform: "uppercase",
  },
  capitalize: {
    textTransform: "capitalize",
  },
  bold: {
    fontFamily: "Helvetica-Bold",
  },
  boldB: {
    fontFamily: "Helvetica-Bold",
    color: "#373796",
  },
  footerPage: {
    position: "absolute",
    bottom: 30,
    left: 0,
    right: 30,
    fontSize: 9,
    textAlign: "right",
  },
  headerSectionDataClient: {
    display: "flex",
    flexDirection: "row",
  },
  sectionDataClient: {
    display: "flex",
    flexDirection: "column",
    marginBottom: 10,
    marginRight: 40,
  },
  headerNameEmp: {
    fontFamily: "Helvetica-Bold",
    alignSelf: "flex-end",
  },
  lowercase: {
    textTransform: "lowercase",
  },
  spacing: {
    marginBottom: 10,
  },
  viewerStyles: {
    height: "100vh",
    width: "100vw",
  },
  boxDataUser: {
    position: "absolute",
    top: "50",
    left: "0",
    width: "100%",
    height: "95",
  },
  containerDataUser: {
    display: "flex",
    flexDirection: "row",
    padding: "5px",
    justifyContent: "flex-start",
    textTransform: "uppercase",
  },
  containerDataUserSpacing: {
    display: "flex",
    flexDirection: "row",
    paddingRight: "5px",
    alignItems: "center",
    justifyContent: "space-between",
  },
  textSpacing: {
    paddingRight: "10px",
  },
  underLine: {
    textDecoration: "underline",
    fontFamily: "Helvetica-Bold",
  },
  boxDataUserSeller: {
    position: "absolute",
    top: "4",
    right: "10",
    width: "380",
    height: "14",
  },
  sectionFooter: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sectionContentFooter: {
    flexGrow: 2,
    flexBasis: 0,
    textTransform: "lowercase",
  },
  sectionContentFooter2: {
    flexGrow: 1,
    flexBasis: 0,
  },
});

export const data = {
  dateQuery: moment().format("YYYY/MM/DD"),
  totalDistribuidor: 1,
  totalCosto: 0,
  totalVenta: 0,
  totalDisponible: 3,
  totalInventario: 1123213,
  address: "Calle 12 # 12-12",
  tel: "123456789",
  web: "reac.simbio@gmail.com",
  proveedor: "SIN PROVEEDOR",
  urlLogo:
    "https://th.bing.com/th/id/R.450ed000220051f0f81c479ba281de0b?rik=9IA5gC8SXO6LvA&pid=ImgRaw&r=0",
  data: [
    {
      product: "DESLIZADOR",
      subTotalDistribuidor: 0,
      secSubTotalDistribuidor: 0,
      secSubTotalCosto: 0,
      SecSubTotalVenta: 0,
      subTotalCosto: 0,
      subTotalVenta: 25000,
      subTotalDisponible: 2,
      subTotalInventario: 50000,
      products: [
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          presentation: "",
          aplication: "",
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          presentation: "",
          distribuidor: 0,
          aplication: "",
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          aplication: "",
          distribuidor: 0,
          presentation: "",
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          aplication: "",
          costo: 0,
          presentation: "",
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          costo: 0,
          presentation: "",
          aplication: "",
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          presentation: "",
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
      ],
    },
    {
      product: "DESLIZADOR",
      subTotalDistribuidor: 0,
      secSubTotalDistribuidor: 0,
      secSubTotalCosto: 0,
      SecSubTotalVenta: 0,
      subTotalCosto: 0,
      subTotalVenta: 25000,
      subTotalDisponible: 2,
      subTotalInventario: 50000,
      products: [
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
        {
          id: 1,
          cod: "36750",
          name: "ACEITE TVS 20W50 4T DURALIFE 1L",
          distribuidor: 0,
          costo: 0,
          venta: 25000,
          disponible: 2,
          inventario: 50000,
        },
      ],
    },
  ],
};
