import { StyleSheet } from "@react-pdf/renderer";
import moment from "moment";

export const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    textTransform: "uppercase",
    paddingTop: 35,
    paddingBottom: 65,
    paddingLeft: 27,
    paddingRight: 30,
    fontSize: 9,
  },
  headerTitle: {
    fontFamily: "Helvetica-Bold",
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  headerTitleContent: {
    fontFamily: "Helvetica-Bold",
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  sectionProducts: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  headerClientName: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerCell: {
    flexGrow: 1,
    flexBasis: 0,
    textDecoration: "underline",
    textTransform: "capitalize",
    marginBottom: 5,
    marginTop: 5,
  },
  headerCell2: {
    flexGrow: 2,
    flexBasis: 0,
    textDecoration: "underline",
    textTransform: "capitalize",
    marginBottom: 5,
    marginTop: 5,
  },
  headerCell3: {
    flexGrow: 3,
    flexBasis: 0,
    textDecoration: "underline",
    textTransform: "capitalize",
    marginBottom: 5,
    marginTop: 5,
  },
  sectionProductsContent: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  contentCell: {
    flexGrow: 1,
    flexBasis: 0,
    paddingBottom: 3,
  },
  contentCell2: {
    flexGrow: 2,
    paddingBottom: 3,
    flexBasis: 0,
  },
  contentCell3: {
    flexGrow: 3,
    flexBasis: 0,
    paddingBottom: 3,
  },
  uppercase: {
    textTransform: "uppercase",
  },
  capitalize: {
    textTransform: "capitalize",
  },
  bold: {
    fontFamily: "Helvetica-Bold",
  },
  footerPage: {
    position: "absolute",
    bottom: 30,
    left: 0,
    right: 30,
    fontSize: 9,
    textAlign: "right",
  },
  headerSectionDataClient: {
    display: "flex",
    flexDirection: "row",
  },
  sectionDataClient: {
    display: "flex",
    flexDirection: "column",
    marginBottom: 10,
    marginRight: 40,
  },
  headerNameEmp: {
    fontFamily: "Helvetica-Bold",
    alignSelf: "flex-end",
  },
  lowercase: {
    textTransform: "lowercase",
  },
  spacing: {
    marginBottom: 10,
  },
});

export const data = {
  dateQuery: moment().format("YYYY/MM/DD"),
  fullName: "DISTRIMOTOS YAMAHA SAS",
  seller: "STEVEN DAVID MANCILLA NIEVA",
  data: [
    {
      id: 1,
      date: "2021-01-01",
      totalStateSell: 2,
      totalStateLost: 2,
      total: 2000000,
      totalLost: 2000000,
      oportunityPerMonth: [
        {
          id: 1,
          clientName: "Juan Sebastian Leal Tascon",
          dateOportunity: "2021-01-01",
          total: 1000000,
          state: "Sin seguimiento",
          finance: "No",
          percentage: "",
          dateLastFollow: "",
        },
        {
          id: 2,
          clientName: "Juan Sebastian Leal Tascon",
          dateOportunity: "2021-01-01",
          total: 1000000,
          state: "VENDIDA",
          finance: "No",
          Percentage: "",
          dateLastFollow: "",
        },
        {
          id: 1,
          clientName: "Juan Sebastian Leal Tascon",
          dateOportunity: "2021-01-01",
          total: 1000000,
          state: "VENDIDA",
          finance: "No",
          Percentage: "",
          dateLastFollow: "",
        },
        {
          id: 1,
          clientName: "Juan Sebastian Leal Tascon",
          dateOportunity: "2021-01-01",
          total: 1000000,
          state: "Sin seguimiento",
          finance: "No",
          Percentage: "",
          dateLastFollow: "",
        },
      ],
    },
    {
      id: 1,
      date: "2021-02-01",
      totalStateSell: 0,
      totalStateLost: 4,
      total: 0,
      totalLost: 4000000,
      oportunityPerMonth: [
        {
          id: 1,
          clientName: "Juan Sebastian Leal Tascon",
          dateOportunity: "2021-01-01",
          total: 1000000,
          state: "Sin seguimiento",
          finance: "No",
          percentage: "",
          dateLastFollow: "",
        },
        {
          id: 1,
          clientName: "Juan Sebastian Leal Tascon",
          dateOportunity: "2021-01-01",
          total: 1000000,
          state: "Sin seguimiento",
          finance: "No",
          Percentage: "",
          dateLastFollow: "",
        },
        {
          id: 1,
          clientName: "Juan Sebastian Leal Tascon",
          dateOportunity: "2021-01-01",
          total: 1000000,
          state: "Sin seguimiento",
          finance: "No",
          Percentage: "",
          dateLastFollow: "",
        },
        {
          id: 1,
          clientName: "Juan Sebastian Leal Tascon",
          dateOportunity: "2021-01-01",
          total: 1000000,
          state: "Sin seguimiento",
          finance: "No",
          Percentage: "",
          dateLastFollow: "",
        },
      ],
    },
  ],
};
